version: '3'
services:
  service1:
    build:
      context: service1
      dockerfile: dockerfile1
      args:
        - APP_NAME=service1 
        - ENV=dev
        - BASE_IMAGE=node:16
    image: node_service:1.1

  service2: 
    build:
      context: .
      dockerfile: dockerfile2
      args:
        - APP_NAME=service2
        - ENV=dev2
        - BASE_IMAGE=node:20
    image: node_service:2.1